name: Generate JSDoc Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: '16'  # O la versión que uses en tu proyecto

      # Instala dependencias
      - name: Install dependencies
        run: npm install

      # Genera la documentación con JSDoc
      - name: Generate JSDoc documentation
        run: npx jsdoc -c jsdoc.json

      # Publica la documentación en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
